/**
 * Service worker for JACOB — merged FCM push handling + app-shell caching.
 *
 * Served by Next.js so the Firebase config can be inlined synchronously
 * at the SW's top level (see PR #332 for the original async-init bug).
 *
 * Why a single SW handles BOTH push and app-shell caching:
 *
 * A scope can only have ONE service-worker registration. Previously
 * the app registered `/sw.js` (app-shell caching, calls skipWaiting on
 * install) AND `/firebase-messaging-sw.js` (FCM, no skipWaiting) at
 * the same `scope: "/"`. Per the SW spec, the second register() call
 * REPLACES the registration's script for that scope. Because `/sw.js`
 * skipWaits aggressively and the FCM SW didn't, `/sw.js` won
 * activation every page load — leaving the active SW with no `push`
 * event handler. Pushes arrived from Apple's gateway, hit the
 * cache-only SW, and were silently dropped. FCM kept reporting
 * `delivered=1` because Apple had accepted the payload upstream.
 *
 * Merging both responsibilities into one SW makes the conflict
 * impossible to recreate. `skipWaiting()` + `clients.claim()` on this
 * SW also force existing devices (which still have the old `/sw.js`
 * cached as their controller) to swap to this new merged SW on the
 * next page load instead of waiting for the PWA to be closed and
 * reopened.
 */

import { NextResponse } from "next/server";

// Pinned to match the SDK version we use in the page bundle. Bump in
// lockstep with `frontend/package.json`'s `firebase` dependency so
// background and foreground messaging stay on the same wire protocol.
const FIREBASE_COMPAT_VERSION = "10.12.2";

// Bump this whenever the cache layout or precache list changes so the
// activate handler purges stale caches under the old name.
const SW_VERSION = "3";

export const dynamic = "force-static";

export async function GET(): Promise<NextResponse> {
  const config = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? "",
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? "",
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "",
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? "",
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "",
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID ?? "",
  };

  const body = `/* generated by app/firebase-messaging-sw.js/route.ts */
/* eslint-disable */

// ── FCM messaging (synchronous init — see file header) ───────────────────
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_COMPAT_VERSION}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_COMPAT_VERSION}/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload) {
  var title = (payload && payload.notification && payload.notification.title) || "JACOB";
  var body = (payload && payload.notification && payload.notification.body) || "";
  self.registration.showNotification(title, {
    body: body,
    icon: "/icons/icon-192x192.png",
    badge: "/icons/badge-96x96.png",
    tag: (payload && payload.collapseKey) || "jacob-push",
  });
});

// ── App-shell caching ────────────────────────────────────────────────────

const CACHE_NAME = "jacob-shell-v${SW_VERSION}";
const PRECACHE_URLS = ["/home", "/manifest.webmanifest"];

self.addEventListener("install", function (event) {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then(function (cache) {
        return cache.addAll(PRECACHE_URLS).catch(function () {
          return undefined;
        });
      })
      .then(function () {
        // Force this SW to take over from any older registration
        // (e.g. the legacy /sw.js or pre-merge /firebase-messaging-sw.js)
        // on the next page load instead of waiting for every existing
        // client to close. Critical for users whose iPhone PWA is still
        // controlled by an old SW that has no push handler.
        return self.skipWaiting();
      })
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches
      .keys()
      .then(function (keys) {
        return Promise.all(
          keys
            .filter(function (k) {
              return k.indexOf("jacob-") === 0 && k !== CACHE_NAME;
            })
            .map(function (k) {
              return caches.delete(k);
            })
        );
      })
      .then(function () {
        return self.clients.claim();
      })
  );
});

self.addEventListener("fetch", function (event) {
  var request = event.request;
  var url = new URL(request.url);

  // Passthrough: cross-origin, Firebase/Firestore SDK, backend API.
  if (
    url.origin !== self.location.origin ||
    url.pathname.indexOf("/api/") === 0 ||
    url.pathname.indexOf("/__/") === 0
  ) {
    return;
  }

  // Stale-while-revalidate: Next.js static chunks (cache-busted by hash).
  if (url.pathname.indexOf("/_next/static/") === 0) {
    event.respondWith(staleWhileRevalidate(request));
    return;
  }

  // Network-first with offline fallback: navigation and app shell.
  if (request.mode === "navigate" || url.pathname.indexOf("/_next/") === 0) {
    event.respondWith(networkFirstWithFallback(request));
    return;
  }
});

function staleWhileRevalidate(request) {
  return caches.open(CACHE_NAME).then(function (cache) {
    return cache.match(request).then(function (cached) {
      var networkPromise = fetch(request).then(function (res) {
        if (res.ok) cache.put(request, res.clone());
        return res;
      });
      return cached || networkPromise;
    });
  });
}

function networkFirstWithFallback(request) {
  return caches.open(CACHE_NAME).then(function (cache) {
    return fetch(request)
      .then(function (res) {
        if (res.ok) cache.put(request, res.clone());
        return res;
      })
      .catch(function () {
        return cache.match(request).then(function (cached) {
          if (cached) return cached;
          return cache.match("/home").then(function (shell) {
            return (
              shell ||
              new Response("Offline", { status: 503, statusText: "Offline" })
            );
          });
        });
      });
  });
}
`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Allow this SW to control the entire origin even though it lives
      // at the root (default scope is already `/`, but spelling it out
      // documents intent and is harmless).
      "Service-Worker-Allowed": "/",
      // Service workers should always revalidate. The browser already
      // bypasses HTTP caching for SW updates by default (24-hour cap),
      // but explicit `no-cache` keeps any intermediary CDN honest.
      "Cache-Control": "no-cache, no-store, must-revalidate",
    },
  });
}
