/**
 * Firebase Messaging Service Worker — served by Next.js so the project
 * config can be inlined synchronously at the SW's top level.
 *
 * Why a route handler instead of a static file in `public/`:
 *
 * The previous SW (`public/firebase-messaging-sw.js`) tried to load its
 * config asynchronously — first by `fetch("/__/firebase/init.json")`
 * (which only classic Firebase Hosting auto-serves; App Hosting does
 * not) and, failing that, by listening for a `postMessage` from the
 * foreground page. Both paths require the SW to be alive while the
 * page is loaded. iOS Safari aggressively backgrounds installed PWAs,
 * so a `push` event almost always arrives when the SW is cold: the
 * SW restarts, runs top-level code with `_messagingReady = false`,
 * the fetch 307s to /onboarding, the postMessage never arrives, and
 * `firebase.messaging()` is never called — so the FCM SDK's internal
 * `push` listener is never registered and the notification is dropped
 * silently. FCM still reports `delivered=1` because Apple's web-push
 * gateway accepted the payload.
 *
 * The fix is to call `firebase.initializeApp(...)` and
 * `firebase.messaging()` SYNCHRONOUSLY at the top of the SW so the
 * push handler is in place before the first `push` event fires. The
 * config values are all `NEXT_PUBLIC_*` (not secret) and are
 * environment-specific, so each deploy inlines its own.
 */

import { NextResponse } from "next/server";

// Pinned to match the SDK version we use in the page bundle. Bump in
// lockstep with `frontend/package.json`'s `firebase` dependency so
// background and foreground messaging stay on the same wire protocol.
const FIREBASE_COMPAT_VERSION = "10.12.2";

export const dynamic = "force-static";

export async function GET(): Promise<NextResponse> {
  const config = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? "",
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? "",
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "",
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? "",
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "",
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID ?? "",
  };

  // JSON.stringify keeps the config opaque to any pattern-based source
  // scanners but is just a literal object expression to the SW runtime.
  const body = `/* generated by app/firebase-messaging-sw.js/route.ts */
/* eslint-disable */
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_COMPAT_VERSION}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_COMPAT_VERSION}/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload) {
  var title = (payload && payload.notification && payload.notification.title) || "JACOB";
  var body = (payload && payload.notification && payload.notification.body) || "";
  self.registration.showNotification(title, {
    body: body,
    icon: "/icons/icon-192x192.png",
    badge: "/icons/badge-96x96.png",
    tag: (payload && payload.collapseKey) || "jacob-push",
  });
});
`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Allow this SW to control the entire origin even though it lives
      // at the root (default scope is already `/`, but spelling it out
      // documents intent and is harmless).
      "Service-Worker-Allowed": "/",
      // Service workers should always revalidate. The browser already
      // bypasses HTTP caching for SW updates by default (24-hour cap),
      // but explicit `no-cache` keeps any intermediary CDN honest.
      "Cache-Control": "no-cache, no-store, must-revalidate",
    },
  });
}
